"""add_audit_log_table

Revision ID: 0a8cf3c8f44d
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 18:05:27.386190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8cf3c8f44d'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('LogId', sa.Integer(), nullable=False),
    sa.Column('ActorId', sa.Integer(), nullable=True),
    sa.Column('Action', sa.String(length=100), nullable=False),
    sa.Column('TargetType', sa.String(length=50), nullable=True),
    sa.Column('TargetId', sa.Integer(), nullable=True),
    sa.Column('Details', sa.Text(), nullable=True),
    sa.Column('IPAddress', sa.String(length=45), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ActorId'], ['users.UserId'], name='fk_audit_log_actor'),
    sa.PrimaryKeyConstraint('LogId')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_tracking_ref'))
        batch_op.drop_constraint(batch_op.f('uq_tickets_tracking_ref'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tickets_TrackingRef'), ['TrackingRef'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_TrackingRef'))
        batch_op.create_unique_constraint(batch_op.f('uq_tickets_tracking_ref'), ['TrackingRef'])
        batch_op.create_index(batch_op.f('ix_tickets_tracking_ref'), ['TrackingRef'], unique=1)

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
