"""Add escalations, admin_notifications, IsActive to users, announcements

Revision ID: da93b30e4fc9
Revises: 
Create Date: 2026-03-07 11:46:54.066510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da93b30e4fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('DepartmentId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.Column('Description', sa.String(length=300), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('DepartmentId'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('users',
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('FullName', sa.String(length=150), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('PasswordHash', sa.String(length=256), nullable=False),
    sa.Column('Role', sa.Enum('Student', 'Staff', 'Admin', name='roleenum'), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('DepartmentId', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DepartmentId'], ['departments.DepartmentId'], name='fk_users_department_id'),
    sa.PrimaryKeyConstraint('UserId'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('announcements',
    sa.Column('AnnouncementId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Message', sa.Text(), nullable=False),
    sa.Column('TargetAudience', sa.String(length=20), nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['CreatedBy'], ['users.UserId'], name='fk_announcements_created_by'),
    sa.PrimaryKeyConstraint('AnnouncementId')
    )
    op.create_table('tickets',
    sa.Column('TicketId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Category', sa.String(length=100), nullable=False),
    sa.Column('Priority', sa.Enum('Low', 'Medium', 'High', name='priorityenum'), nullable=False),
    sa.Column('Status', sa.Enum('Submitted', 'Assigned', 'InProgress', 'PendingInfo', 'Resolved', 'Rejected', name='statusenum'), nullable=False),
    sa.Column('StudentId', sa.Integer(), nullable=False),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.Column('DepartmentId', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('ResolvedAt', sa.DateTime(), nullable=True),
    sa.Column('FeedbackRating', sa.Integer(), nullable=True),
    sa.Column('FeedbackComment', sa.Text(), nullable=True),
    sa.Column('FeedbackAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['DepartmentId'], ['departments.DepartmentId'], name='fk_tickets_department_id'),
    sa.ForeignKeyConstraint(['StaffId'], ['users.UserId'], name='fk_tickets_staff_id'),
    sa.ForeignKeyConstraint(['StudentId'], ['users.UserId'], name='fk_tickets_student_id'),
    sa.PrimaryKeyConstraint('TicketId')
    )
    op.create_table('admin_notifications',
    sa.Column('NotificationId', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Message', sa.String(length=500), nullable=False),
    sa.Column('IsRead', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('TicketId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TicketId'], ['tickets.TicketId'], name='fk_admin_notifications_ticket_id'),
    sa.PrimaryKeyConstraint('NotificationId')
    )
    op.create_table('escalation_requests',
    sa.Column('EscalationId', sa.Integer(), nullable=False),
    sa.Column('TicketId', sa.Integer(), nullable=False),
    sa.Column('RequestedById', sa.Integer(), nullable=False),
    sa.Column('TargetDeptId', sa.Integer(), nullable=False),
    sa.Column('Reason', sa.Text(), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ResolvedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RequestedById'], ['users.UserId'], name='fk_escalation_requested_by'),
    sa.ForeignKeyConstraint(['TargetDeptId'], ['departments.DepartmentId'], name='fk_escalation_dept_id'),
    sa.ForeignKeyConstraint(['TicketId'], ['tickets.TicketId'], name='fk_escalation_ticket_id'),
    sa.PrimaryKeyConstraint('EscalationId')
    )
    op.create_table('ticket_updates',
    sa.Column('UpdateId', sa.Integer(), nullable=False),
    sa.Column('TicketId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Comment', sa.Text(), nullable=False),
    sa.Column('StatusChange', sa.Enum('Submitted', 'Assigned', 'InProgress', 'PendingInfo', 'Resolved', 'Rejected', name='updatestatusenum'), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('IsReplyThread', sa.Boolean(), nullable=False),
    sa.Column('ParentUpdateId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ParentUpdateId'], ['ticket_updates.UpdateId'], name='fk_ticket_updates_parent_id'),
    sa.ForeignKeyConstraint(['TicketId'], ['tickets.TicketId'], name='fk_ticket_updates_ticket_id'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], name='fk_ticket_updates_user_id'),
    sa.PrimaryKeyConstraint('UpdateId')
    )
    op.create_table('attachments',
    sa.Column('AttachmentId', sa.Integer(), nullable=False),
    sa.Column('TicketId', sa.Integer(), nullable=True),
    sa.Column('UpdateId', sa.Integer(), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('FilePath', sa.String(length=500), nullable=False),
    sa.Column('UploadedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['TicketId'], ['tickets.TicketId'], name='fk_attachments_ticket_id'),
    sa.ForeignKeyConstraint(['UpdateId'], ['ticket_updates.UpdateId'], name='fk_attachments_update_id'),
    sa.PrimaryKeyConstraint('AttachmentId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('ticket_updates')
    op.drop_table('escalation_requests')
    op.drop_table('admin_notifications')
    op.drop_table('tickets')
    op.drop_table('announcements')
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
