from app.models.department          import Department             # noqa: F401
from app.models.user                import User                   # noqa: F401
from app.models.ticket              import Ticket                 # noqa: F401
from app.models.ticket_update       import TicketUpdate           # noqa: F401
from app.models.attachment          import Attachment             # noqa: F401
from app.models.announcement        import Announcement           # noqa: F401
from app.models.admin_notification  import AdminNotification      # noqa: F401
from app.models.escalation          import EscalationRequest      # noqa: F401
from app.models.user_notification   import UserNotification       # noqa: F401
from app.models.reassignment_request import ReassignmentRequest   # noqa: F401
from app.models.reopen_request      import ReopenRequest          # noqa: F401
from app.models.ticket_flag         import TicketFlag, FlaggedTicket  # noqa: F401
from app.models.audit_log           import AuditLog                   # noqa: F401
from app.models.ticket_vote         import TicketVote                 # noqa: F401
from app.models.ticket_comment      import TicketComment              # noqa: F401
from app.models.comment_attachment  import CommentAttachment          # noqa: F401
from app.models.comment_vote        import CommentVote                # noqa: F401
from app.models.user_preference     import UserPreference             # noqa: F401
from app.models.pending_registration import PendingRegistration       # noqa: F401